Nuvoton-Israel/u-boot

arch/arm/dts/nuvoton-npcm750-buv.dts
Signed-off-by: Brian Ma <chma0@nuvoton.com>
=> npcm7xx: runbmc: buv: add DTS for BUV board

arch/arm/dts/nuvoton-common-npcm7xx.dtsi, arch/arm/dts/nuvoton-npcm750-buv-pincfg.dtsi, arch/arm/dts/nuvoton-npcm750-buv.dts, arch/arm/dts/nuvoton-npcm750-evb.dts, arch/arm/dts/nuvoton-npcm750-olympus-pincfg.dtsi, arch/arm/dts/nuvoton-npcm750-olympus.dts
Signed-off-by: Brian Ma <chma0@nuvoton.com>
=> dts: npcm7xx: add common and pincfg dtsi

arch/arm/dts/nuvoton-npcm730-gis-pincfg.dtsi, arch/arm/dts/nuvoton-npcm730-gis.dts
Add GIS u-boot dts and pinctl files.
Signed-off-by: Fran Hsu <Fran.Hsu@quantatw.com>
=> Commit u-boot DTS files for the GIS project.

arch/arm/dts/nuvoton-npcm730-gis-pincfg.dtsi, arch/arm/dts/nuvoton-npcm730-gis.dts
Change the polarity of GPIO143.
Add definition of GPI-20/199.
Signed-off-by: Fran Hsu <Fran.Hsu@quantatw.com>
=> u-boot: GIS system dts update.

cmd/Kconfig, cmd/mem.c, cmd/standalone_test.c
Signed-off-by: Medad CChien <ctcchien@nuvoton.com>
=> u-boot: Add config to enable saving log in header

cmd/mem.c
Note: 1.If you want to do MFG test in uboot,
Please Use IGPS to append Test Bin after uboot
2.Command:
"stdtst" will list all test bin appended after uboot
and will print all the info in header
"stdtst exec #" will copy test bin to target address
and execute then save resutl in header and uboot-env
3.Each Test bin is aligned with 0x1000,
and there is a header for each Test bin, header size is 0x100
4.Header
offset  size  data
0x0     0x8   TestBINTag
0x8     0x4   CodeSize
0xC     0x4   DestAddr
0x10    0x40  Description
0x50    0x4   TestResult
0x54    0xAC  Reserved
Signed-off-by: Medad CChien <ctcchien@nuvoton.com>
=> 	u-boot: mfg test: Remove saving mtest result

arch/arm/dts/nuvoton-npcm730-kudo-pincfg.dtsi, arch/arm/dts/nuvoton-npcm730-kudo.dts
Signed-off-by: Lancelot Kao <lancelot.kao@fii-usa.com>
=> add Fii kudo project dts & dtsi files

arch/arm/dts/nuvoton-npcm730-gis-pincfg.dtsi, arch/arm/dts/nuvoton-npcm730-gis.dts
commit quanta-gis DTS v1.05 to Nuvoton repo.
Signed-off-by: Fran Hsu <Fran.Hsu@quantatw.com>
=> meta-gis: update quanta-gis DTS to v1.05.

arch/arm/dts/nuvoton-npcm730-gbs-pincfg.dtsi
=> dts: npcm730 GBS: add event-clear for GPIO146 (fans-efuse)

arch/arm/dts/nuvoton-common-npcm7xx.dtsi, arch/arm/dts/nuvoton-npcm750-buv.dts, drivers/usb/host/ehci-npcm.c, drivers/usb/host/ohci-npcm.c
=> Npcm750 v2021.04

arch/arm/dts/Makefile, arch/arm/dts/nuvoton-npcm750-buv.dts, arch/arm/dts/nuvoton-npcm750-olympus-pincfg.dtsi, arch/arm/dts/nuvoton-npcm750-olympus.dts, drivers/pinctrl/nuvoton/pinctrl-npcm7xx.c
=> Npcm7xx  v2021.04

drivers/watchdog/Kconfig, drivers/watchdog/npcm_wdt.c
=> wdt:npcm : modify coding style

drivers/watchdog/npcm_wdt.c
=> wdt:npcm : modify wdt struct

drivers/watchdog/npcm_wdt.c
=> wdt:npcm : remove common.h

drivers/watchdog/npcm_wdt.c
=> wdt: npcm: lower-case hex change and remove delay function

arch/arm/dts/nuvoton-npcm845-evb.dts, cmd/Kconfig, cmd/net.c, drivers/net/designware.c, drivers/net/designware.h, drivers/net/phy/ncsi.c, include/net.h, net/net.c
note: Add CONFIG_PHY_NCSI, CONFIG_CMD_NCSI
to support NCSI
=> npcm8xx: net: support NCSI

arch/arm/dts/nuvoton-common-npcm7xx.dtsi, board/nuvoton/poleg/poleg.c, drivers/mmc/npcm_sdhci.c
=> npcm7xx: modify board init and sdhci driver

arch/arm/dts/nuvoton-common-npcm7xx.dtsi, drivers/clk/nuvoton/clk_npcm7xx.c
use a more modular to modify driver
Signed-off-by: Jim Liu <JJLIU0@nuvoton.com>
=> clk: npcm7xx: update driver

arch/arm/dts/nuvoton-common-npcm7xx.dtsi, arch/arm/dts/nuvoton-npcm750-buv.dts, arch/arm/dts/nuvoton-npcm750.dtsi, arch/arm/dts/nuvoton-npcm7xx-dev.dtsi
=> dst: npcm750 : update dts

arch/arm/dts/nuvoton-common-npcm7xx.dtsi, arch/arm/dts/nuvoton-npcm7xx-u-boot.dtsi, drivers/mmc/npcm_sdhci.c, drivers/pinctrl/nuvoton/pinctrl-npcm7xx.c
=> Npcm v2021.04

arch/arm/include/asm/arch-npcm8xx/gfx.h, cmd/Kconfig, cmd/Makefile, cmd/gfx_test.c
Add gfx test command.
(porting from npcm7xx-v2019.01 5b12664)
Usage:
dcache off
gfx 2 off
gfx 3
=> cmd: Add gfx test command

drivers/pinctrl/nuvoton/pinctrl-npcm7xx.c
if set persist-enable the regmap_update_bits is error
=> pinctrl: npcm7xx: fix set persist error

arch/arm/include/asm/arch-npcm7xx/rst.h, arch/arm/include/asm/arch-npcm8xx/rst.h, drivers/pinctrl/nuvoton/pinctrl-npcm7xx.c, drivers/pinctrl/nuvoton/pinctrl-npcm8xx.c
add reset type detect and persist setting.
=> pinctrl: npcm: add reset type detect

drivers/net/designware.c, drivers/net/phy/broadcom.c
Add BCM54612E phy for NPCM7xx BUV RGMII
=> phy: nuvoton: add BCM54612E  phy support

drivers/net/designware.c
=> Npcm v2023.10

drivers/net/designware.c
=> npcm2021 net patch

arch/arm/dts/Makefile, arch/arm/dts/nuvoton-npcm730-gbs-pincfg.dtsi, arch/arm/dts/nuvoton-npcm730-gbs.dts, arch/arm/dts/nuvoton-npcm730-gis-pincfg.dtsi, arch/arm/dts/nuvoton-npcm730-gis.dts, arch/arm/dts/nuvoton-npcm730-kudo-pincfg.dtsi, arch/arm/dts/nuvoton-npcm730-kudo.dts, arch/arm/dts/nuvoton-npcm730-mori-pincfg.dtsi, arch/arm/dts/nuvoton-npcm730-mori.dts, arch/arm/dts/nuvoton-npcm7xx-pinctrl.dtsi
=> dts: npcm7xx: Add customer dts support

arch/arm/dts/nuvoton-npcm845-pincfg.dtsi
=> dts: fix nuvoton-npcm845-pincfg.dtsi typo

arch/arm/dts/nuvoton-npcm845-yosemite4.dts
Add initial support for npcm845 yosemite4.
=> arm: dts: Add initial support for npcm845 yosemite4

arch/arm/dts/nuvoton-npcm845-yosemite4-pincfg.dtsi, arch/arm/dts/nuvoton-npcm845-yosemite4.dts
Add pincfg dtsi to clear gpio event.
=> arm: dts: npcm845-yosemite4: add yosemite4-pincfg dtsi

drivers/gpio/npcm_sgpio.c
Fix SGPIO drvier build warning and format adjustment
=> gpio: npcm: Fix SGPIO build warning and format adjustment

drivers/pinctrl/nuvoton/pinctrl-npcm8xx.c
Clear all gpio events to avoid unexpected interrupts during kernel booting.
=> pinctrl: npcm8xx: clear all gpio events
