- include/linux/compiler-gcc8.h
Signed-off-by: kfting <kfting@nuvoton.com>
> meta-evb-npcm750: fix the build break due to gcc upgrade in openbmc 2.6

- include/configs/poleg.h
Set bootargs to make linux kernel trigger panic on oops, and reboot 20 seconds after panic.
This is crucial for production environment where the BMC needs to recover from kernel panics.
Tested:
root:~# cat /proc/sys/kernel/panic
20
root:~# cat /proc/sys/kernel/panic_on_oops
1
Manually trigger kernel panic and observe BMC rebooted after 20
seconds:
root@arcadia:~# echo c > /proc/sysrq-trigger
Signed-off-by: Kun Yi <kunyi@google.com>
> nuvoton: poleg.h: Add kernel reboot on oops/panic to bootargs

- arch/arm/dts/nuvoton-npcm730-gbs-pincfg.dtsi
- arch/arm/dts/nuvoton-npcm730-gbs.dts
add the missing input gpios initialization
> dts:npcm730 GBS: add the missing GPIs initial

- arch/arm/dts/nuvoton-npcm730-gbs-pincfg.dtsi
GPIO59 is for interrupt and need to clear events after reboot
> dts: npcm730 GBS: add event clear to GPIO59

- arch/arm/dts/nuvoton-npcm730-gbs-pincfg.dtsi
- arch/arm/dts/nuvoton-npcm730-gbs.dts
1. add event clear to GPIO05/57/58/69/120/121
2. initialize GPIO74 as output low
> dts: npcm730 GBS: add event clear to some GPIs and init GPIO74

- arch/arm/dts/nuvoton-npcm730-gbs-pincfg.dtsi
- arch/arm/dts/nuvoton-npcm730-gbs.dts
It should be only set output-high for GPIO91
> dts: npcm730 GBS: fix the GPIO91 setting

- drivers/pinctrl/nuvoton/pinctrl-npcm7xx.c
In original design, we cannot change gpio state after persist state
is set until power reset. Now we can change gpio state if we disalbe
gpio persist state first.
Signed-off-by: Brian Ma <chma0@nuvoton.com>
> driver: pinctrl-npcm7xx: allow change gpio persist state

- drivers/crypto/npcm750_sha.c
Signed-off-by: Medad CChien <ctcchien@nuvoton.com>
> NPCM750: SHA Hash Engine: Enable and Reset Module in hw_sha_init()

- scripts/dtc/dtc-lexer.l
This patch removes symbols dups that occurs at linkage stage.
Signed-off-by: Anton D. Kachalov <gmouse@google.com>
> Fix u-boot build

- arch/arm/dts/nuvoton-npcm730-kudo-pincfg.dtsi
- arch/arm/dts/nuvoton-npcm730-kudo.dts
Modified GPIOs in u-boot dts/dtsi for Fii kudo project to match the current configuration in the Fii kudo kernel dts.
Signed-off-by: Brandon Ong <brandon.ong@fii-usa.com>
> dts: npcm730 kudo: update gpios in dts/dtsi

- arch/arm/mach-npcm850/include/mach/arbel_espi.h
- board/nuvoton/arbel/arbel.c
1. To enable espi support, add the following setting in the target dts
config {
espi-channel-support = <0xf>;
};
Signed-off-by: kfting <kfting@nuvoton.com>
> board : nuvoton : espi support

- arch/arm/dts/nuvoton-npcm730-gsz-pincfg.dtsi
- arch/arm/dts/nuvoton-npcm730-gsz.dts
1.Change GPIO32 to output-low.
2.Change GPIO187 to output-high.
3.Update the eSPI setting.
Signed-off-by: Fran Hsu <fran.hsu@quantatw.com>
> dts: npcm730 GSZ: update the GPIO default setting

- arch/arm/dts/nuvoton-npcm730-kudo-pincfg.dtsi
Modified GPIO203 add persist-enable config in u-boot dtsi for Fii kudo
project to match the current configuration in the Fii kudo u-boot dtsi.
Signed-off-by: Mustafa Shehabi <mustafa.shehabi@fii-na.com>
> dts: npcm730 kudo: update GPIO203 in dtsi

- arch/arm/dts/nuvoton-npcm750-buv.dts
- board/nuvoton/poleg/poleg.c
update DTS and poleg.c for mmc1 move to mmc0
fix issues:
mmc0: error -84 whilst initialising MMC card (linux)
unable to select a mode : -70 error while read data from mmc (UBoot)
Signed-off-by: Brian Ma <chma0@nuvoton.com>
> npcm7xx: fix mmc probe fail

- arch/arm/dts/nuvoton-npcm730-mori-pincfg.dtsi
- arch/arm/dts/nuvoton-npcm730-mori.dts
Create the DTS and pinctrl DTSI files for NPCM730 machine to use
in the Mori project.
Signed-off-by: Charles Boyer <Charles.Boyer@fii-usa.com>
> dts: npcm730 mori: Add Fii Mori project DTS and DTSI files

- drivers/mtd/spi/Kconfig
- drivers/mtd/spi/spi-nor-ids.c
add entry to support Google Hoth devices.
Signed-off-by: Jason Ling <jasonling@google.com>
> spi-nor-id: add support for Google-Hoth

- arch/arm/dts/nuvoton-npcm845-evb.dts
- drivers/spi/npcm_fiu_spi.c
Default value is 3.3v for FIU3.
If 1.8v is required, please modify the following property value in fiu3 node.
vqspi-microvolt = <1800000>;
Signed-off-by: Tyrone Ting <kfting@nuvoton.com>
> dts: nuvoton-npcm845: enable FIU3 voltage configuration

- include/configs/poleg.h
This is a follow up patch to https://github.com/Nuvoton-Israel/u-boot/pull/10. After enabling kernel panic on oops, we'd like to store the panic dmesg, which requires reserving a fixed location in ram.
> configs: poleg: Reserve memory for kernel panic dmesg

- drivers/mtd/spi/Kconfig
- drivers/mtd/spi/spi_flash_ids.c
This is backporting https://github.com/Nuvoton-Israel/u-boot/pull/89 to the 2019 branch.
> mtd: spi: Add Google compatible flash IDs

- board/nuvoton/arbel/Kconfig
Correct CONFIG_SYS_MEM_TOP_HIDE value to 0xB300000 (179MB), which reserve memory for ECC/GFX/OPTEE/TIP/CP as follows.
+-------------+-----------+---------------+--------------+
|   Column    | Size (MB) | Offset in Hex | Offset in MB |
+-------------+-----------+---------------+--------------+
| DDR TOP     |           |    40000000   |     1024     |
| DDR ECC     |    128    |    38000000   |      896     |
| GFX         |     16    |    37000000   |      880     |
| OPTEE       |     16    |    36000000   |      864     |
| Reserved    |      1    |    35F00000   |      863     |
| TIP own DDR |     16    |    34F00000   |      847     |
| CP          |      2    |    34D00000   |      845     |
+-------------+-----------+---------------+--------------+
|  sum 179  |
+-----------+ …
> board: nuvoton: arbel: Correct CONFIG_SYS_MEM_TOP_HIDE value

- drivers/spi/npcm_fiu_spi.c
Symptom:
drivers/spi/npcm_fiu_spi.c: In function 'npcm_fiu_spi_probe': drivers/spi/npcm_fiu_spi.c:390:3: warning: implicit declaration of function 'device_get_supply_regulator' [-Wimplicit-function-declaration] device_get_supply_regulator(bus, "vqspi-supply", &vqspi_supply); ^~~~~~~~~~~~~~~~~~~~~~~~~~~
Root cause:
Lack of declaration power/regulator.h include file.
Solution:
Adding the “#include <power/regulator.h>” to fix this kind of warnings.
Signed-off-by: Tim Lee <timlee660101@gmail.com>
> drivers: spi: fix compiler warnings from npcm_fiu_spi_probe

- drivers/gpio/npcm750_gpio.c
- drivers/pinctrl/nuvoton/pinctrl-npcm7xx.c
The default output state may be different to request, change the configuration sequence to avoid glitch.
> gpio: npcm7xx: output state before enabling the output

- arch/arm/include/asm/arch-npcm8xx/gcr.h
- board/nuvoton/arbel/arbel.c
int non tip mode, BMC first power on with PORST+CORST. the gpio status will wrong.
> mpcm8xx: fix reset reason issue for bootup

- drivers/i2c/i2c-npcm.c
Symptom:
When setting i2c speed 400k that got failed:
U-Boot>i2c speed 400000
Setting bus speed to 400000 Hz
Support standard mode only
Failure changing bus speed (-22)
Root cause:
Default only support Standard mode.
Solution:
Enable support Fast mode.
Tested:
U-Boot>i2c dev 0
Setting bus to 0
I2C bus 0 ready. speed=100000, base=0xf0080000, apb=62500000 U-Boot>i2c speed
Current bus speed=100000
U-Boot>i2c speed 400000
Setting bus speed to 400000 Hz
U-Boot>i2c speed
Current bus speed=400000
> i2c: npcm: enable support Fast mode

- cmd/fuse.c
In poleg, fuse read would print dummy byte data,
U-Boot>fuse read 0 0 16
Reading bank 0:
Byte 0x0000: 3cd11300 3cd11300 3cd11300 3cd11300 3cd11300 3cd11300 3cd11300 3cd11300 3cd11300 3cd11300 3cd11300 3cd11300 3cd11300 3cd11300 3cd11300 3cd11300
In arbel, fuse read would print correct data.
U-Boot>fuse read 0 0 16
Reading bank 0:
Byte 0x0000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> cmd: fuse: casting u32 to u8 if CONFIG_NPCM

- include/configs/arbel.h
when u-boot enable CONFIG_SYS_BOOT_RAMDISK_HIGH, rootfs image relocated from FIU address space to memory address before jump to kernel.
since Arbel reserved memory from 0x00000000 to 0x06200000 for tip image, and rootfs image may too large that cannot found a suitable location before 128MB(0x8000000), so increase mapping size from 128MB to 192MB.
> configs: arbel: increase u-boot mapping size

- cmd/Kconfig
- cmd/pxe.c
- net/bootp.c
- net/dhcpv6.c
cherry-pick changes from upstream for PXE support
net: Get pxe config file from dhcp option 209 u-boot/u-boot@9195395 
net: dhcp6: Fix OPT_BOOTFILE_PARAM parsing. u-boot/u-boot@b2369a1
> Pr dhcp pxe

- include/configs/arbel.h
Due to we will enable WD1 about 120 seconds after bootblock finish DDR initialization, add stopwdt command once we need stay in U-Boot.
> env: add stopwdt command in default environment

- board/nuvoton/poleg_evb/poleg_evb.c
There is build failure in function 'last_stage_init',
and this failure noticed only "gbs" machine.
/data0/jenkins/workspace/ci-openbmc/distro/ubuntu/label
/docker-builder/target/gbs/build/work/gbs-openbmc-linux-gnueabi
/u-boot-nuvoton/v2023.10+git/git/board/nuvoton/
poleg_evb/poleg_evb.c :79:9:
error: implicit declaration of function 'arch_preboot_os'
Required all commits from this chain to recreate the failure.
https://gerrit.openbmc.org/c/openbmc/openbmc/+/72220/9
> board: poleg: fix build failure in last_stage_init

- board/nuvoton/arbel_evb/Kconfig
- board/nuvoton/arbel_evb/arbel_evb.c
- env/sf.c
Add support to load the proper u-boot env data according to normal or recovery boot source.
Tested:
Normal mode log: Detected Normal mode. Using CS 0 for env
Recovery mode log: Detected Recovery mode. Using CS 1 for env
> board: arbel_evb: support select CS for env

- board/nuvoton/arbel_evb/Kconfig
env/Kconfig:398:warning:
ignoring type redefinition of 'ENV_SPI_CS' from 'hex' to 'integer'
> board: arbel_evb: fix build warning for env config

- include/configs/arbel_yosemite4.h
Align the default offset of rofs and rwfs from upstream. The current default offset for FLASH_ROFS_OFFSET and FLASH_RWFS_OFFSET are set as follows:
FLASH_ROFS_OFFSET:flash-131072 ?= "10240"
FLASH_RWFS_OFFSET:flash-131072 ?= "98304"
We need to change the default rofs size to 86MB (0xA00000) and rwfs size to 32MB (0x6000000) for yosemite4 project.
Tested:
root@bmc:~# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 08000000 00010000 "bmc"
mtd1: 002c0000 00010000 "u-boot"
mtd2: 00040000 00010000 "u-boot-env"
mtd3: 00600000 00010000 "kernel"
mtd4: 05600000 00010000 "rofs"
mtd5: 02000000 00010000 "rwfs"
mtd6: 08000000 00010000 "bmc2"
> config: modify size of rofs and rwfs for yosemite4

- common/Kconfig.boot
- common/image-fit.c
- drivers/crypto/fsl/Kconfig
calculate_hash() would try to select the appropriate hashing function
by a if/elseif contruct. But that is exactly why hash_lookup_algo()
exists, so use it instead.
This does mean that we now have to 'select HASH' to make sure we get
the hash_lookup_algo() symbol. However, the change makes sense because
even basic FITs will have to deal with "hash" nodes.
My only concern is that the 'select SPL_HASH' might cause some
platform to grow above its SPL size allowance
Signed-off-by: Alexandru Gagniuc <mr.nuke.me@gmail.com>
[trini: Make FSL_CAAM be implied only on ARM && SPL]
Signed-off-by: Tom Rini <trini@konsulko.com>
Signed-off-by: Tim Lee <chli30@nuvoton.com>
> image: Drop if/elseif hash selection in calculate_hash()

- common/image-fit.c
The hash algorithm selection was streamlined in commit 92055e138f28
("image: Drop if/elseif hash selection in calculate_hash()"). Said
commit kept the call to cpu_to_uimage() to convert the CRC to big
endian format.
This would have been correct when calling crc32_wd(). However, the
->hash_func_ws member of crc32 points to crc32_wd_buf(), which already
converts the CRC to big endian. On a little endian host, doing both
conversions results in a little-endian CRC. This is incorrect.
To remedy this, simply drop the call to cpu_to_uimage(), thus only
doing the byte-order conversion once.
Fixes: 92055e138f28 ("image: Drop if/elseif hash selection in
calculate_hash()")
Tested-by: Tom Rini <trini@konsulko.com>
Signed-off-by: Alexandru Gagniuc <mr.nuke.me@gmail.com>
Signed-off-by: Tim Lee …
> image: Avoid erroneous double byte-swap in CRC value

- cmd/usb_mass_storage.c
- drivers/usb/host/usb-uclass.c
- include/usb.h
ums command can specify the usb controller but the usb uclass driver always use the first UCLASS_USB device. Add uclass driver API to let ums can set the specific usb controller to be used for the usb gadget.
> cmd: ums: find the correct usb controller for ums command
